import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";

// import profilePic from "../../public/images/profile/profile-pic-5.png";
// import profilePic from "../../public/images/profile/profile-pic4.png";
// import profilePic from "../../public/images/profile/profile-picTwo.png";
// import profilePic from "../../public/images/profile/profile-pic-3.png";
import profilePic from "../../public/images/profile/profile-pic-3-round.png";
// import profilePic from "../../public/images/profile/developer-pic-profile.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Fridas portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="CodeBucks"
                className="w-full h-auto border-solid border-2 border-pink-100 hover:border-dotted  rounded-full transition ease-in-out delay-150 duration-300 hover:-translate-y-1 hover:scale-110"
              ></Image>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
