import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-profile.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Fridas portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout>
          <div className="flex items-center justify-between w-full">
            <div>
              <Image
                src={profilePic}
                alt="CodeBucks"
                className="w-full h-auto"
              ></Image>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
